create table acc_owner_follower (acc_owner int8 not null, follower int8 not null);
create table "booking" (id int8 not null, booking_date_time timestamp, booking_status int4, date_from date, date_till date, total_price int4, product_id int8, user_id int8, primary key (id));
create table "booking_calendar" (id int8 not null, booked boolean not null, date date, product_id int8, user_id int8, primary key (id));
create table "calendar" (id int8 not null, booked boolean not null, date date, product_id int8, user_id int8, primary key (id));
create table "category" (id int8 not null, name varchar(255), primary key (id));
create table "category_field" (category_id int8 not null, field_id int8 not null, is_visible boolean not null, primary key (category_id, field_id));
create table "field" (id int8 not null, name varchar(255), primary key (id));
create table "field_product" (field_id int8 not null, product_id int8 not null, value varchar(255), primary key (field_id, product_id));
create table "image" (id int8 not null, public_id varchar(255), url varchar(255), primary key (id));
create table "image_product" (id int8 not null, order_number int2, image_id int8, product_id int8, primary key (id));
create table "image_user" (id int8 not null, order_number int2, image_id int8, image_user_id int8, primary key (id));
create table "location" (id int8 not null, x float8 not null, y float8 not null, primary key (id));
create table "paid_ad" (id int8 not null, date_from date, date_till date, paid_ad_waiting_list_id int8, primary key (id));
create table "paid_ad_waiting_list" (id int8 not null, is_paid boolean not null, price_per_day float8 not null, product_id int8, primary key (id));
create table "passport_data" (id int8 not null, authority varchar(255), date_of_issue date, tin varchar(255), primary key (id));
create table "permission" (id int8 not null, description varchar(255), name varchar(255) not null, primary key (id));
create table "product" (id int8 not null, active boolean, book_date_from date not null, book_date_till date not null, clicked_num int4 not null, creation_time timestamp, currency varchar(255), description varchar(255), minimum_booking_number_day int4 not null, price int4 not null, title varchar(255) not null, category_id int8, location_id int8, user_id int8, primary key (id));
create table "question" (id int8 not null, answer varchar(255), question varchar(255), primary key (id));
create table "registered_address" (id int8 not null, apartment_number int4, city_or_village varchar(255), district varchar(255), house_number int4, region varchar(255), street varchar(255), primary key (id));
create table "residence_address" (id int8 not null, apartment_number int4, city_or_village varchar(255), district varchar(255), house_number int4, region varchar(255), street varchar(255), primary key (id));
create table "review" (id int8 not null, date_time timestamp, star int2 not null, text varchar(255), product_id int8, user_id int8, primary key (id));
create table "role" (id int8 not null, name varchar(255) not null, primary key (id));
create table role_permission (role_id int8 not null, permission_id int8 not null, primary key (role_id, permission_id));
create table "user" (id int8 not null, code_expiration_date timestamp, date_of_birth date, email varchar(255), first_name varchar(255), is_registration_complete boolean, is_verified_by_tech_support boolean, last_name varchar(255), middle_name varchar(255), password varchar(255), phone_number varchar(255), provider varchar(255), provider_id varchar(255), reset_password_code int4, status varchar(255), passport_data_id int8, registered_address_id int8, residence_address_id int8, role_id int8, primary key (id));
create table user_favorite (user_id int8 not null, product_id int8 not null);
create table "view" (id int8 not null, view_num int4 not null, category_id int8, user_id int8, primary key (id));

alter table if exists "calendar" add constraint FKiof4j44vpqu1nmfe4hmfjtalj foreign key (product_id) references "product";
alter table if exists "calendar" add constraint FKide48qn2pjnp65hr5ej8mtalx foreign key (user_id) references "user";
alter table if exists "permission" drop constraint if exists UK_2ojme20jpga3r4r79tdso17gi;
alter table if exists "permission" add constraint UK_2ojme20jpga3r4r79tdso17gi unique (name);
alter table if exists "role" drop constraint if exists UK_8sewwnpamngi6b1dwaa88askk;
alter table if exists "role" add constraint UK_8sewwnpamngi6b1dwaa88askk unique (name);

create sequence booking_seq start 1 increment 1;
create sequence calendar_seq start 1 increment 1;
create sequence category_seq start 1 increment 1;
create sequence field_seq start 1 increment 1;
create sequence image_product_seq start 1 increment 1;
create sequence image_seq start 1 increment 1;
create sequence image_user_seq start 1 increment 1;
create sequence location_seq start 1 increment 1;
create sequence paid_ad_seq start 1 increment 1;
create sequence paid_ad_waiting_list_seq start 1 increment 1;
create sequence passport_data_seq start 1 increment 1;
create sequence permission_seq start 1 increment 1;
create sequence product_seq start 1 increment 1;
create sequence question_seq start 1 increment 1;
create sequence registered_address_seq start 1 increment 1;
create sequence residence_address_seq start 1 increment 1;
create sequence review_seq start 1 increment 1;
create sequence role_seq start 1 increment 1;
create sequence user_seq start 1 increment 1;
create sequence view_seq start 1 increment 1;

alter table if exists acc_owner_follower add constraint FKnc0bv6i9q2617ff05blf41uxh foreign key (follower) references "user";
alter table if exists acc_owner_follower add constraint FKh0817vvp2ucqvwp3sb042p8kd foreign key (acc_owner) references "user";
alter table if exists "booking" add constraint FKo26c6t5ukm9k5flg1lbbmjb7t foreign key (product_id) references "product";
alter table if exists "booking" add constraint FK7d7kgstrv4tyx63ugpnwrgrr2 foreign key (user_id) references "user";
alter table if exists "booking_calendar" add constraint FK4xonx2t5wq5v13ix2jjpfprar foreign key (product_id) references "product";
alter table if exists "booking_calendar" add constraint FK4pci9dxh9yy1etth75m476sy8 foreign key (user_id) references "user";
alter table if exists "category_field" add constraint FKhw8ho4fxc6ckogid28w3dot4x foreign key (category_id) references "category";
alter table if exists "category_field" add constraint FKfuwk6i8tubvcg2h0t2nlt91fu foreign key (field_id) references "field";
alter table if exists "field_product" add constraint FKetxwjfge0j4ertqouql0in6qe foreign key (field_id) references "field";
alter table if exists "field_product" add constraint FKey504r3qcvd7hmvm4a8fmqo1n foreign key (product_id) references "product";
alter table if exists "image_product" add constraint FKady516jlsg5tpm0y3hy7vtvkx foreign key (image_id) references "image";
alter table if exists "image_product" add constraint FKbdw02wic3pbvehkeybwpt1u4w foreign key (product_id) references "product";
alter table if exists "image_user" add constraint FKfqi6tlf3yofhsghtur5fcjro8 foreign key (image_id) references "image";
alter table if exists "image_user" add constraint FKrro1ewecdvkv0feiydooq085s foreign key (image_user_id) references "user";
alter table if exists "paid_ad" add constraint FKjblifrowhi6gvyc3txy45c3dr foreign key (paid_ad_waiting_list_id) references "paid_ad_waiting_list";
alter table if exists "paid_ad_waiting_list" add constraint FKooowhy6iv0fy2xjhk6a4ms7aj foreign key (product_id) references "product";
alter table if exists "product" add constraint FKqys3wf25o4da9h0vqcpnnjfmt foreign key (category_id) references "category";
alter table if exists "product" add constraint FKjtx66pw7nkyk6elvwoc6bl5a foreign key (location_id) references "location";
alter table if exists "product" add constraint FK1tj468ad94xehdp4osd96t8jg foreign key (user_id) references "user";
alter table if exists "review" add constraint FK8x25iltcokacjswskpkppdepw foreign key (product_id) references "product";
alter table if exists "review" add constraint FKhruntmasmfx37yvoo35v910qt foreign key (user_id) references "user";
alter table if exists role_permission add constraint FK52c21e4ibh5h9dribrdpvc20n foreign key (permission_id) references "permission";
alter table if exists role_permission add constraint FK47iwf79t28gwdhw566xgjliat foreign key (role_id) references "role";
alter table if exists "user" add constraint FKnmv4gyay5c05n1bl6mlp8tcr5 foreign key (passport_data_id) references "passport_data";
alter table if exists "user" add constraint FKaes61wbod3rd3kq88lvursuvr foreign key (registered_address_id) references "registered_address";
alter table if exists "user" add constraint FKjqtbom8g1ncyihfp64k76p1v7 foreign key (residence_address_id) references "residence_address";
alter table if exists "user" add constraint FK_USER_ROLE foreign key (role_id) references "role";
alter table if exists user_favorite add constraint FKnm2kb9u6oad9f7b17ny44y4xr foreign key (product_id) references "product";
alter table if exists user_favorite add constraint FK64vf6pkiqrjoje257i90ty6o0 foreign key (user_id) references "user";
alter table if exists "view" add constraint FKm3ui6tyat45tv6qrabn2j32a6 foreign key (category_id) references "category";
alter table if exists "view" add constraint FKlwabo8tfqc081jo4gd2d7ma9f foreign key (user_id) references "user";
